# Secret key will be generated every time on app start if not set
SECRET_KEY = None

GRAPHITE_PORT = 8080
CARBON_PORT = 2003

# One can provide multiple retention rules via CARBON_STORAGE_SCHEMA_*
# options, see carbon docs. Rules are applied in name sort order.
# Value consist of 'pattern|retentions'
CARBON_STORAGE_SCHEMA_CARBON = r'^carbon\.|60s:1d,5m:7d,10m:30d'
CARBON_STORAGE_SCHEMA_ZDEFAULT = r'.*|60s:7d,5m:30d,30m:90d,1h:1y'

# Storage aggregations, value consist of 'pattern|xFilesFactor|aggregationMethod'
CARBON_STORAGE_AGG_MIN = r'\.min$|0.1|min'
CARBON_STORAGE_AGG_MAX = r'\.max$|0.1|max'
CARBON_STORAGE_AGG_SUM = r'\.count$|0|sum'
CARBON_STORAGE_AGG_ZDEFAULT = r'.*|0.2|average'

CC_PID_DIR = '/data'
CC_DATABASE = 'whisper'
CC_ENABLE_LOGROTATION = True
CC_USER = ''
CC_MAX_CACHE_SIZE = 50000
CC_MAX_UPDATES_PER_SECOND = 50
CC_MAX_UPDATES_PER_SECOND_ON_SHUTDOWN = 1000
CC_MAX_CREATES_PER_MINUTE = 50
CC_MIN_TIMESTAMP_RESOLUTION = 1
CC_MIN_TIMESTAMP_LAG = 0
CC_LINE_RECEIVER_INTERFACE = '0.0.0.0'
CC_LINE_RECEIVER_PORT = CARBON_PORT
CC_ENABLE_UDP_LISTENER = False
CC_UDP_RECEIVER_INTERFACE = '0.0.0.0'
CC_UDP_RECEIVER_PORT = CARBON_PORT
CC_PICKLE_RECEIVER_INTERFACE = '0.0.0.0'
CC_PICKLE_RECEIVER_PORT = 0
CC_PROTOBUF_RECEIVER_INTERFACE = '0.0.0.0'
CC_PROTOBUF_RECEIVER_PORT = 0
CC_MAX_RECEIVER_CONNECTIONS = 'inf'
CC_USE_INSECURE_UNPICKLER = False
CC_CACHE_QUERY_INTERFACE = '0.0.0.0'
CC_CACHE_QUERY_PORT = 7002
CC_USE_FLOW_CONTROL = True
CC_METRIC_CLIENT_IDLE_TIMEOUT = 120
CC_LOG_UPDATES = False
CC_LOG_CREATES = False
CC_LOG_CACHE_HITS = False
CC_LOG_CACHE_QUEUE_SORTS = False
CC_CACHE_WRITE_STRATEGY = 'timesorted'
CC_WHISPER_AUTOFLUSH = False
CC_WHISPER_SPARSE_CREATE = False
CC_WHISPER_FALLOCATE_CREATE = True
CC_WHISPER_LOCK_WRITES = False
CC_WHISPER_FADVISE_RANDOM = True
CC_CERES_NODE_CACHING_BEHAVIOR = 'all'
CC_CERES_SLICE_CACHING_BEHAVIOR = 'latest'
CC_CERES_MAX_SLICE_GAP = 80
CC_CERES_LOCK_WRITES = False
CC_USE_WHITELIST = False
CC_CARBON_METRIC_PREFIX = 'carbon'
CC_CARBON_METRIC_INTERVAL = 60
CC_ENABLE_AMQP = False
CC_AMQP_VERBOSE = False
CC_AMQP_HOST = 'localhost'
CC_AMQP_PORT = 5672
CC_AMQP_VHOST = '/'
CC_AMQP_USER = 'guest'
CC_AMQP_PASSWORD = 'guest'
CC_AMQP_EXCHANGE = 'graphite'
CC_AMQP_METRIC_NAME_IN_BODY = False
CC_BIND_PATTERNS = '#'
CC_GRAPHITE_URL = 'http://127.0.0.1:{}'.format(GRAPHITE_PORT)
CC_ENABLE_TAGS = True
CC_TAG_UPDATE_INTERVAL = 100
CC_TAG_BATCH_SIZE = 100
CC_TAG_QUEUE_SIZE = 10000
